name: scouting_tracker_beach_volley
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  auto_size_text: ^3.0.0
  shared_preferences: ^2.2.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  flutter_inset_box_shadow: ^1.0.8
  cloud_firestore: ^4.8.5
  azlistview: ^2.0.0
  image_picker: ^1.0.2
  firebase_storage: ^11.2.6
  sqflite: ^2.3.0
  flutter_svg: ^2.0.9
  connectivity_plus: ^5.0.2
  get: ^4.6.5
  cached_network_image: ^3.3.0
  pdf: ^3.10.7
  path_provider: ^2.1.2
  open_file: ^3.3.2
  url_launcher: ^6.2.4
  pdf_viewer_plugin: ^2.0.1
  permission_handler: ^11.3.0
  advance_pdf_viewer2: ^2.0.5+1
  screenshot: ^2.3.0
  printing: ^5.12.0
  


  
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/core/assets/images/logo.png"
  


  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0
 
flutter:

 
  uses-material-design: true
  generate: true
 
  assets:
    - lib/core/assets/images/
    - lib/core/assets/icons/
    - lib/core/assets/icons/wind_direction_icons/

  
  fonts:
    - family: MyFont
      fonts:
        - asset: lib/core/assets/fonts/Roboto-Black.ttf
 