// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9OmfgdBf9_nJRt9ynmklPeRfz8ZLyRvk',
    appId: '1:853452171464:web:8d8ac45c04945a5a619dfd',
    messagingSenderId: '853452171464',
    projectId: 'scouting-tracker-beach-v-808cc',
    authDomain: 'scouting-tracker-beach-v-808cc.firebaseapp.com',
    storageBucket: 'scouting-tracker-beach-v-808cc.appspot.com',
    measurementId: 'G-HQ7GK5JSXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj1QEF5-VwoqwNLg7iZ8Naw_RrNph_Boo',
    appId: '1:853452171464:android:bcc894f4bbd28484619dfd',
    messagingSenderId: '853452171464',
    projectId: 'scouting-tracker-beach-v-808cc',
    storageBucket: 'scouting-tracker-beach-v-808cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBINghN6q2EJKJzZj_rJchLNJjmH6RKtiY',
    appId: '1:853452171464:ios:1525a7b1025bdc18619dfd',
    messagingSenderId: '853452171464',
    projectId: 'scouting-tracker-beach-v-808cc',
    storageBucket: 'scouting-tracker-beach-v-808cc.appspot.com',
    iosClientId: '853452171464-ca8mibvdpid6iqnl4jc3uh53khtl1dko.apps.googleusercontent.com',
    iosBundleId: 'com.example.scoutingTrackerBeachVolley',
  );
}
